use std::{fs, path::PathBuf};

#[test]
fn main_window_can_manage_session_events_and_reset_session() {
    let capability: serde_json::Value =
        serde_json::from_str(include_str!("../capabilities/main-window.json"))
            .expect("main-window capability is valid JSON");
    let permissions = capability["permissions"]
        .as_array()
        .expect("permission list");

    assert!(
        permissions
            .iter()
            .any(|value| value == "core:event:allow-listen")
    );
    assert!(
        permissions
            .iter()
            .any(|value| value == "core:event:allow-unlisten")
    );
    assert!(
        permissions
            .iter()
            .any(|value| value == "allow-reset-session")
    );

    let permission_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("permissions/autogenerated/reset_session.toml");
    let reset_permission = fs::read_to_string(permission_path).expect("reset permission exists");
    assert!(reset_permission.contains("identifier = \"allow-reset-session\""));
}

#[test]
fn main_window_can_use_only_the_explicit_screen_assistance_commands() {
    let capability: serde_json::Value =
        serde_json::from_str(include_str!("../capabilities/main-window.json"))
            .expect("main-window capability is valid JSON");
    let permissions = capability["permissions"]
        .as_array()
        .expect("permission list");
    for permission in [
        "allow-get-screen-capture-capabilities",
        "allow-list-screen-capture-targets",
        "allow-start-screen-capture",
        "allow-cancel-screen-capture",
        "allow-crop-screen-capture",
        "allow-discard-screen-capture",
        "allow-start-screenshot-assistance",
    ] {
        assert!(
            permissions.iter().any(|value| value == permission),
            "missing permission {permission}"
        );
    }
}

#[test]
fn main_window_can_manage_shortcut_bindings_through_typed_commands() {
    let capability: serde_json::Value =
        serde_json::from_str(include_str!("../capabilities/main-window.json"))
            .expect("main-window capability is valid JSON");
    let permissions = capability["permissions"]
        .as_array()
        .expect("permission list");
    for (permission, command) in [
        ("allow-get-shortcut-bindings", "get_shortcut_bindings"),
        ("allow-update-shortcut-bindings", "update_shortcut_bindings"),
    ] {
        assert!(
            permissions.iter().any(|value| value == permission),
            "missing permission {permission}"
        );
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join(format!("permissions/autogenerated/{command}.toml"));
        let generated = fs::read_to_string(path).expect("shortcut permission exists");
        assert!(generated.contains(&format!("commands.allow = [\"{command}\"]")));
    }
}

#[test]
fn main_window_can_select_microphones_and_update_window_appearance() {
    let capability: serde_json::Value =
        serde_json::from_str(include_str!("../capabilities/main-window.json"))
            .expect("main-window capability is valid JSON");
    let permissions = capability["permissions"]
        .as_array()
        .expect("permission list");

    for (permission, command) in [
        ("allow-list-audio-input-devices", "list_audio_input_devices"),
        ("allow-get-voice-input-settings", "get_voice_input_settings"),
        ("allow-get-window-opacity", "get_window_opacity"),
        ("allow-set-window-opacity", "set_window_opacity"),
    ] {
        assert!(
            permissions.iter().any(|value| value == permission),
            "missing permission {permission}"
        );
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join(format!("permissions/autogenerated/{command}.toml"));
        let generated = fs::read_to_string(path).expect("permission file exists");
        assert!(generated.contains(&format!("commands.allow = [\"{command}\"]")));
    }
}
