use std::{fs, path::PathBuf};

#[test]
fn main_window_can_manage_session_events_and_reset_session() {
    let capability: serde_json::Value =
        serde_json::from_str(include_str!("../capabilities/main-window.json"))
            .expect("main-window capability is valid JSON");
    let permissions = capability["permissions"]
        .as_array()
        .expect("permission list");

    assert!(
        permissions
            .iter()
            .any(|value| value == "core:event:allow-listen")
    );
    assert!(
        permissions
            .iter()
            .any(|value| value == "core:event:allow-unlisten")
    );
    assert!(
        permissions
            .iter()
            .any(|value| value == "allow-reset-session")
    );

    let permission_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("permissions/autogenerated/reset_session.toml");
    let reset_permission = fs::read_to_string(permission_path).expect("reset permission exists");
    assert!(reset_permission.contains("identifier = \"allow-reset-session\""));
}
